name: Sync to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://dula22438:$HF_TOKEN@huggingface.co/spaces/dula22438/Dubai-property-advisor
          git lfs push hf main --all
          git push hf main --force
